---
- hosts: localhost
  become_method: sudo
  connection: local

  roles:
    - { role: geerlingguy.ntp, become: true }
    - { role: christophermancini.docker }

  vars:
    #docker_images:
    #  - golang:latest

  tasks:
    - name: utils
      package: "name={{ item }}"
      with_items:
        - vim

    - name: Add Vagrant user to Docker Group
      user:
        name: vagrant
        groups:
          - docker
        append: yes

    - name: Add helper things to bashrc
      lineinfile:
        path: /home/vagrant/.bashrc
        line: "{{ item }}"
      with_items:
        - "alias ll='ls -al --color=auto'"
        - "export GOPATH=$GOPATH:~/code/go:~/code/concourse"
        - "export PATH=$PATH:~/go/bin:~/code/go/bin:~/code/concourse/bin:/usr/lib/postgresql/9.6/bin"
