---
- hosts: localhost
  become_method: sudo
  connection: local

  roles:
    - { role: geerlingguy.ntp, become: true }
    - { role: geerlingguy.nodejs }
    - { role: christophermancini.docker }
    - { role: joshualund.golang }
    - { role: telusdigital.mariadb, mariadb_server: yes, database_password: "vagrant", project: "wdwdb" }

  vars:
    ansible_container: true
    ansible_container_engines:
      - docker

    #docker_images:
    #  - mariadb:latest
    #  - golang:latest

    go_tarball: "go1.9.3.linux-amd64.tar.gz"
    go_tarball_checksum: "sha256:a4da5f4c07dfda8194c4621611aeb7ceaab98af0b38bfb29e1be2ebb04c3556c"
    go_version_target: "go version go1.9.3 linux/amd64"

  tasks:
    - name: utils
      package: "name={{ item }}"
      with_items:
        - vim

    - name: Add Vagrant user to Docker Group
      user:
        name: vagrant
        groups:
          - docker
        append: yes

    - name: Add helper things to bashrc
      lineinfile:
        path: /home/vagrant/.bashrc
        line: "{{ item }}"
      with_items:
        - "alias ll='ls -al --color=auto'"
