---
- hosts: localhost
  become_method: sudo
  connection: local

  vars:
    ansible_container: true
    ansible_container_engines:
      - docker

    #docker_images:
    #  - mariadb:latest
    #  - golang:latest

  roles:
    - { role: geerlingguy.ntp, become: true }
    - { role: geerlingguy.nodejs }
    - { role: christophermancini.docker }
    #- { role: ansible }

  tasks:
    - name: Add Vagrant user to Docker Group
      user:
        name: vagrant
        groups: docker
        append: yes

    #- name: Create a redis container
    #  docker_container:
    #    name: mariadb
    #    image: mariadb:latest
    #    state: present
    #    env:
    #      MYSQL_ROOT_PASSWORD: money
    #      MYSQL_DATABASE: cryptotrader
    #    exposed_ports:
    #      - 3306
